### ISSUE TITLE
DataFrame.Collect() returns IEnumerable<Row>

### ISSUE THREAD

**Issue by mrericrichter** [GoEddie/spark-connect-dotnet#11]
To be compatible with Microsoft's Spark .Net solution, `DataFrame.Collect()` should return `IEnumerable<Row>` instead of `List<object[]>.`
The `Row` class should provide `Get(string columnName)` and `Get(int index)` methods that return `object` and that throw an exception when the given `columnName` or `index` are not available.

**Comment by GoEddie** [comment]
fixed in build 16
