### ISSUE TITLE
Column index operator of DataFrame throws if column is not available

### ISSUE THREAD

**Issue by mrericrichter** [GoEddie/spark-connect-dotnet#12]
The `public Column this[string name]` method of the `DataFrame` class should throw an exception if the given column `name` is not part of the DataFrame. The exception message should include the name of the missing column.

This allows errors in the user's Spark code to be found right where they occur. Otherwise, errors about missing columns could pop up at very late stages and it might be very difficult to find the error.

**Comment by GoEddie** [comment]
I checked in PySpark and this is different behaviour so I will add it but put it behind an option

**Comment by GoEddie** [comment]
Fixed in build 16 - but you will need to set this option for it to work:

```csharp
spark.Conf.Set("spark.connect.dotnet.validatethiscallcolumnname", "true");
```

See: https://github.com/GoEddie/spark-connect-dotnet/blob/main/docs/options.md
