### ISSUE TITLE
DataFrame.Agg() supports multiple expressions

### ISSUE THREAD

**Issue by mrericrichter** [GoEddie/spark-connect-dotnet#19]
Could you please add a second parameter to `DataFrame.Agg()` that accepts `params Column[] expressions` so that the overall method signature becomes `DataFrame.Agg(Column, params Column[] )`? This would be compatible with Microsoft's Spark DotNet solution.

**Comment by GoEddie** [comment]
Fixed and on nuget.org as 3.5.1-build.17
