### ISSUE TITLE
DataFrame.Join(): use IEnumerable instead of List in parameters

### ISSUE THREAD

**Issue by mrericrichter** [GoEddie/spark-connect-dotnet#7]
In the DataFrame.Join() methods, use IEnumerable instead of List in the 'on' parameter to be compatible with Microsoft Spark DotNet and to follow the standard 'use the least specific type in arguments' rule.

**Comment by GoEddie** [comment]
Hi, seems reasonable I’ll switch to IEnumerable

**Comment by GoEddie** [comment]
Fixed in: https://github.com/GoEddie/spark-connect-dotnet/releases/tag/v3.5.1-build.15 please reopen if this isn't what you meant!
