### ISSUE TITLE
Static 'Window' class

### ISSUE THREAD

**Issue by mrericrichter** [GoEddie/spark-connect-dotnet#8]
In the Microsoft Spark DotNet implementation, the 'Window' class provides static methods such as 'PartitionBy()'. 
Could we also have these static methods to be compatible with Microsoft's solution and to use Spark Connect DotNet as a drop-in replacement?

**Comment by GoEddie** [comment]
The other thing I changed is Read/Write are properties like Pyspark  - I’m tempted to provide a couple of different SparkSession/DataFrame to allow drop in replacement for the old package

**Comment by GoEddie** [comment]
Fixed in: https://github.com/GoEddie/spark-connect-dotnet/releases/tag/v3.5.1-build.15 please reopen if this isn't what you meant!
